spring:
  profiles:
    active: template
  shell:
    context:
      close: true
    history:
      name: ./logs/shell-history.log
    command:
      quit:
        enabled: false
      version:
        show-git-short-commit-id: true
        show-git-commit-time: true
  servlet:
    multipart:
      #最大文件阈值
      max-file-size: 500KB
      #最大请求阈值
      max-request-size: 500KB
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
    time-zone: UTC
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  data:
    mongodb:
      # 打开自动索引生成（否则数据库内唯一索引不生效
      auto-index-creation: true
  freemarker:
    check-template-location: false
  # 缓存配置，使用caffeine缓存框架，缓存时长为5分钟，最大缓存数量500
  cache:
    cache-names: arkLevel, arkLevels, copilotPage
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=300s
server:
  # 8848钛金接口.jpg
  port: 8848
  tomcat:
    #限制post表单最大为30KB
    max-http-form-post-size: 30KB
  compression:
    enabled: true

logging:
  file:
    name: ./logs/latest.log
  logback:
    rollingpolicy:
      max-history: 14
      clean-history-on-start: true

maa-copilot:
  info:
    # 这几个参数应在编译时生成，不宜修改
    commit:
      abbreviated-id: @commitAbbreviatedId@
      date-time: @commitDateTime@